apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: app-ts-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1 #deployment
    kind: Deployment
    name: app-ts
  minReplicas: 6
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 #default 5 min
      policies: 
        - type: Pods #cadency
          value: 2
          periodSeconds: 15  
    #     - type: Percent
    #       value: 20
    #       periodSeconds: 15
    #   selectPolicy: Min #Max

    scaleUp:
      stabilizationWindowSeconds: 5
      policies: 
        - type: Pods #cadency
          value: 2
          periodSeconds: 5
