apiVersion: v1                # Versão da API do Kubernetes.
kind: Secret                  # Tipo do recurso: Secret (usado para armazenar dados sensíveis).

metadata:
  name: app-ts-secrets        # Nome do Secret (referenciado no Deployment).

type: Opaque                  # Tipo genérico de Secret (padrão para dados arbitrários em base64).
                             # TODO: estudar outros tipos como:
                             # - kubernetes.io/basic-auth
                             # - kubernetes.io/dockerconfigjson
                             # - kubernetes.io/service-account-token

data:
  API_KEY: "c2FmYXNkZmZnZHNmZzMyNDUzNDZ5ZGZndmRmc3kzMjVkc2YK"
                             # Dados sensíveis devem estar codificados em base64.
                             # Neste caso, API_KEY é uma chave codificada em base64.
