apiVersion: v1
kind: PersistentVolume

metadata:
  name: fist-pv
  labels:
    name: fist-pv

spec:
  capacity:
    storage: 5Gi  # Define a capacidade do volume persistente.
  accessModes:
    - ReadWriteOnce  # O volume pode ser montado como leitura e escrita por um único nó.
                    # Pode ser alterado para ReadOnlyMany, ReadWriteMany, ReadWriteOncePod dependendo do caso de uso.
  persistentVolumeReclaimPolicy: Delete  # Define o que acontece com o volume quando o PVC é deletado (Delete, Retain, Recycle).
  storageClassName: standard  # Nome da StorageClass associada a este PV
  hostPath:
    path: /mnt/data  # Caminho no host onde o volume será montado.